# Generated by Django 4.1.8 on 2023-04-23 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='UserId',
            field=models.CharField(default='null', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patients',
            name='UserId',
            field=models.CharField(default='null', max_length=15),
            preserve_default=False,
        ),
    ]
